<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>btn_Login</name>
   <tag></tag>
   <elementGuidId>e19e7311-ea7f-4e93-a42b-9bd8ed108b50</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.view.ViewGroup[@content-desc=&quot;test-LOGIN&quot;]</value>
      <webElementGuid>f1ddd33e-97ee-4b8b-93b5-ed0f959dddd4</webElementGuid>
   </webElementProperties>
   <locator>//android.view.ViewGroup[@content-desc=&quot;test-LOGIN&quot;]</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
