<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>txt_Username</name>
   <tag></tag>
   <elementGuidId>6834a9ab-df54-4ee4-8738-0e087b623e3c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.EditText[@content-desc=&quot;test-Username&quot;]</value>
      <webElementGuid>32d80688-a5de-4fc5-86c0-6ca25fa2cb00</webElementGuid>
   </webElementProperties>
   <locator>//android.widget.EditText[@content-desc=&quot;test-Username&quot;]</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
